language: node_js
node_js:
  - "lts/*"
sudo: required
dist: trusty
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn run lint
  - yarn run test
  - yarn run dist
after_success: 'npm run coveralls'

deploy:
  - provider: npm
    skip_cleanup: true
    email: "wxsms@foxmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "dist/uiv.min.js"
    skip_cleanup: true
    on:
      tags: true
